export const IS_LOGIN = 'IS_LOGIN'
export const REQUEST_USER = 'REQUEST_USER'
export const RECEIVE_USER = 'RECEIVE_USER'
export const RECEIVE_EXTRA = 'RECEIVE_EXTRA'
export const CHANGE_IMAGE = 'CHANGE_IMAGE'
